In [ ]:
import numpy as np
import time

print("="*60)
print(" NUMPY SPEED DEMONSTRATION")
print("="*60)

# Test with regular Python lists
size = 1000000
python_list1 = list(range(size))
python_list2 = list(range(size))

start_time = time.time()
python_result = [a + b for a, b in zip(python_list1, python_list2)]
python_time = time.time() - start_time

print(f"\n⏱️  Python Lists: {python_time:.4f} seconds")

# Test with NumPy arrays
numpy_array1 = np.arange(size)
numpy_array2 = np.arange(size)

start_time = time.time()
numpy_result = numpy_array1 + numpy_array2
numpy_time = time.time() - start_time

print(f"⚡ NumPy Arrays: {numpy_time:.4f} seconds")
print(f"\n🚀 NumPy is {python_time/numpy_time:.1f}x FASTER!")
print("\nThis is why we use NumPy for AI/ML work!")

 NUMPY SPEED DEMONSTRATION

⏱️  Python Lists: 0.0699 seconds
⚡ NumPy Arrays: 0.0025 seconds

🚀 NumPy is 28.2x FASTER!

This is why we use NumPy for AI/ML work!


In [2]:
import numpy as np

print("\n" + "="*60)
print(" NUMPY OPERATIONS FOR AI/ML")
print("="*60)

# Sample data: daily sales for a week
daily_sales = np.array([100, 150, 200, 180, 220, 190, 210])

# 1. BASIC STATISTICS (use these ALL the time)
print("\n📊 Statistical Analysis:")
print(f"Total Sales: ${np.sum(daily_sales):,}")
print(f"Average Sales: ${np.mean(daily_sales):,.2f}")
print(f"Median Sales: ${np.median(daily_sales):,.2f}")
print(f"Std Deviation: ${np.std(daily_sales):,.2f}")
print(f"Min Sales: ${np.min(daily_sales)}")
print(f"Max Sales: ${np.max(daily_sales)}")
print(f"Sales Range: ${np.max(daily_sales) - np.min(daily_sales)}")

# 2. ARITHMETIC OPERATIONS (element-wise)
print("\n💰 Business Calculations:")

# Apply 10% growth to all days
projected_sales = daily_sales * 1.10
print(f"With 10% growth: {projected_sales}")

# Calculate profit (assuming 40% profit margin)
profit = daily_sales * 0.40
print(f"Daily Profit (40% margin): {profit}")

# Subtract costs
costs = np.array([50, 60, 70, 65, 75, 68, 72])
net_profit = daily_sales - costs
print(f"Net Profit: {net_profit}")

# 3. BOOLEAN INDEXING (filtering data)
print("\n🔍 Filtering Data:")

# Find days with sales > $180
high_sales_days = daily_sales > 180
print(f"Days with sales > $180: {high_sales_days}")
print(f"Actual values: {daily_sales[high_sales_days]}")
print(f"Number of high-sales days: {np.sum(high_sales_days)}")

# Multiple conditions: sales between $150 and $200
medium_sales = (daily_sales >= 150) & (daily_sales <= 200)
print(f"Sales between $150-$200: {daily_sales[medium_sales]}")

# 4. AGGREGATIONS (super useful for predictions)
print("\n📈 Advanced Analytics:")

# Cumulative sum (running total)
cumulative = np.cumsum(daily_sales)
print(f"Cumulative Sales: {cumulative}")

# Percentage of total
percentages = (daily_sales / np.sum(daily_sales)) * 100
print(f"% of Total Sales: {percentages.round(1)}%")

# Moving average (smoothing for trends)
window = 3
moving_avg = np.convolve(daily_sales, np.ones(window)/window, mode='valid')
print(f"3-day Moving Average: {moving_avg.round(1)}")

# 5. WORKING WITH 2D ARRAYS
print("\n📊 Matrix Operations (Multiple Products):")

# Sales data: 3 products × 5 days
sales_matrix = np.array([
    [100, 120, 110, 130, 125],  # Product A
    [80, 90, 85, 95, 88],        # Product B
    [150, 160, 155, 170, 165]    # Product C
])

print("Sales Matrix (Products × Days):")
print(sales_matrix)

# Total sales per product (sum across columns)
total_per_product = np.sum(sales_matrix, axis=1)
print(f"\nTotal per Product: {total_per_product}")

# Total sales per day (sum across rows)
total_per_day = np.sum(sales_matrix, axis=0)
print(f"Total per Day: {total_per_day}")

# Average sales per product
avg_per_product = np.mean(sales_matrix, axis=1)
print(f"Average per Product: {avg_per_product.round(1)}")

# Which product sells best?
best_product = np.argmax(total_per_product)
print(f"\nBest Selling Product: Product {chr(65+best_product)} (index {best_product})")


 NUMPY OPERATIONS FOR AI/ML

📊 Statistical Analysis:
Total Sales: $1,250
Average Sales: $178.57
Median Sales: $190.00
Std Deviation: $38.33
Min Sales: $100
Max Sales: $220
Sales Range: $120

💰 Business Calculations:
With 10% growth: [110. 165. 220. 198. 242. 209. 231.]
Daily Profit (40% margin): [40. 60. 80. 72. 88. 76. 84.]
Net Profit: [ 50  90 130 115 145 122 138]

🔍 Filtering Data:
Days with sales > $180: [False False  True False  True  True  True]
Actual values: [200 220 190 210]
Number of high-sales days: 4
Sales between $150-$200: [150 200 180 190]

📈 Advanced Analytics:
Cumulative Sales: [ 100  250  450  630  850 1040 1250]
% of Total Sales: [ 8.  12.  16.  14.4 17.6 15.2 16.8]%
3-day Moving Average: [150.  176.7 200.  196.7 206.7]

📊 Matrix Operations (Multiple Products):
Sales Matrix (Products × Days):
[[100 120 110 130 125]
 [ 80  90  85  95  88]
 [150 160 155 170 165]]

Total per Product: [585 438 800]
Total per Day: [330 370 350 395 378]
Average per Product: [117.   87.6 1

In [16]:
import numpy as np

print("="*60)
print(" PRACTICE: CUSTOMER PURCHASE ANALYSIS")
print("="*60)

# Create sample customer data
np.random.seed(42)
num_customers = 100

# Customer purchase amounts ($)
purchases = np.random.uniform(20, 500, size=num_customers)

ages = np.random.randint(18, 70, size=num_customers)

items = np.random.randint(1, 20, size=num_customers)

print(f"\n📊 Analyzing {num_customers} customers...")

# YOUR TASKS:
# 1. Calculate average purchase amount
avg_purchase = np.mean(purchases)
print(f"\n1️⃣Average Purchase: ${avg_purchase:.2f}")

# 2. Find customers who spent more than $300 (high-value customers)
high_value = purchases > 300
num_high_value = np.sum(high_value)
high_value_avg = np.mean(purchases[high_value])
print(f"\n2️⃣ High-Value Customers (>$300):")
print(f"   Count: {num_high_value}")
print(f"   Avg Spend: ${high_value_avg:.2f}")

# 3. Calculate average spend by age group
young = (ages >= 18) & (ages < 30)
middle = (ages >= 30) & (ages < 50)
older = (ages >= 50)

print(f"\n3️⃣ Average Spend by Age Group:")
print(f"   18-29: ${np.mean(purchases[young]):.2f} ({np.sum(young)} customers)")
print(f"   30-49: ${np.mean(purchases[middle]):.2f} ({np.sum(middle)} customers)")
print(f"   50+:   ${np.mean(purchases[older]):.2f} ({np.sum(older)} customers)")

# 4. Find correlation between items purchased and total spend
correlation = np.corrcoef(items, purchases)[0, 1]
print(f"\n4️⃣ Correlation (items vs spend): {correlation:.3f}")
if correlation > 0.5:
    print("   ✓ Strong positive correlation - more items = higher spend")
elif correlation > 0.3:
    print("   ~ Moderate correlation")
else:
    print("   ✗ Weak correlation")
    
# 5. Identify top 10 customers
top_10_indices = np.argsort(purchases)[-10:]
top_10_amounts = purchases[top_10_indices]
print(f"\n5️⃣ Top 10 Customers")
for i, (idx, amount) in enumerate(zip(top_10_indices, top_10_amounts), 1):
    print(f"   #{i}: Customer {idx} - ${amount:.2f}")
    
print("\n" + "="*60)
print(" ANALYSIS COMPLETE!")
print("="*60)

 PRACTICE: CUSTOMER PURCHASE ANALYSIS

📊 Analyzing 100 customers...

1️⃣Average Purchase: $245.69

2️⃣ High-Value Customers (>$300):
   Count: 40
   Avg Spend: $395.99

3️⃣ Average Spend by Age Group:
   18-29: $238.92 (23 customers)
   30-49: $242.67 (36 customers)
   50+:   $252.13 (41 customers)

4️⃣ Correlation (items vs spend): 0.031
   ✗ Weak correlation

5️⃣ Top 10 Customers
   #1: Customer 53 - $449.52
   #2: Customer 43 - $456.47
   #3: Customer 55 - $462.50
   #4: Customer 52 - $470.96
   #5: Customer 33 - $475.47
   #6: Customer 1 - $476.34
   #7: Customer 34 - $483.50
   #8: Customer 50 - $485.40
   #9: Customer 11 - $485.56
   #10: Customer 69 - $493.71

 ANALYSIS COMPLETE!
